# Generated by Django 5.2 on 2025-04-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
